/* DO NOT EDIT THIS FILE - it is machine generated */

#include "../../../../../../../../Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/jni.h"
/* Header for class android_serialport_api_SerialPort */

#ifndef _Included_android_serialport_api_SerialPort
#define _Included_android_serialport_api_SerialPort
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jobject JNICALL
Java_com_senjucao_serialport_1api_serialport_SerialPort_nativeOpen(JNIEnv *env, jobject instance,
                                                                   jstring path_, jint baudrate,
                                                                   jint parity, jint dataBits,
                                                                   jint stopBit, jint flags);
JNIEXPORT void JNICALL
Java_com_senjucao_serialport_1api_serialport_SerialPort_nativeClose(JNIEnv *env, jobject instance);

#ifdef __cplusplus
}
#endif
#endif
